name: Build and upload MC Pack


on:
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            
            - name: Build mcaddon files.
              run: |
                  tmp=(*_BP)
                  zip -r "release.mcpack" "$tmp"
            - name: Upload Release File
              uses: djnicholson/release-action@v2.11
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  release-name: 'Climbable Chains Addon'
                  tag-name: 'latest-build'
                  asset-name: 'release.mcpack'
                  file: 'release.mcpack'
